# Generated by Django 5.1.1 on 2024-11-04 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("seller", "0002_cartbooks_cart"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="item",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="user",
        ),
        migrations.DeleteModel(
            name="CartBooks",
        ),
        migrations.DeleteModel(
            name="Cart",
        ),
    ]
