# Generated by Django 5.1.1 on 2024-12-19 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0002_payment_is_transaction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="is_transaction",
        ),
    ]
