# Generated by Django 5.1.1 on 2024-11-10 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("buyer", "0003_payment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
