# Generated by Django 5.1.1 on 2024-12-19 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buyer", "0004_delete_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="buyer",
            name="is_transaction",
            field=models.BooleanField(default=False),
        ),
    ]
