name: Deploy to EC2
on:
  push:
    branches: [main]  # Trigger on pushes to the "main" branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # The Actions runner (VM) that executes the steps
    steps:
      # Connect to EC2 via SSH and update code
      - name: Deploy code to EC2
        uses: appleboy/ssh-action@v1.0.7  # Popular SSH action for GitHub Actions
        with:
          host: ${{ secrets.EC2_IP }}       # EC2 public IP (stored in GitHub Secrets)
          username: ubuntu                  # Default Ubuntu username
          key: ${{ secrets.SSH_PRIVATE_KEY }} # SSH private key (as a secret)
          script: |  # Commands to run on EC2
            cd Book-Store-DjangoRestFrameWork  # Navigate to your app directory
            git pull origin main  # Pull latest code
            pip install -r requirenments.txt           # Install dependencies (if needed, e.g., Node.js)

            pkill -f "python manage.py runserver 0.0.0.0:8000" # Stop the existing server
            
            nohup python manage.py runserver 0.0.0.0:8000 & # Start the server again